version: '3.8'

services:

  my-db-server:
    image: mysql:8.0
    container_name: big_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bigsize_db

    ports:
      - "3306:3306"

  my-phpmyadmin:
    image: phpmyadmin:latest
    container_name: big_pma
    restart: always

    ports:
      - "8081:80"